project:
  type: website

website:
  title: "Documentação"
  navbar:
    left:
      - href: index.qmd
        # text: Home
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  docx:
    toc: true
    number-sections: true
    highlight-style: github
  pdf:
    toc: false
    number-sections: true
    colorlinks: true